name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t myapp .
        docker images

    - name: Push Docker image to Docker Hub (facultatif)
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker push myapp
